// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"database/sql"
	"time"
)

type Detail struct {
	Title           string
	Version         string
	Processingsize  int64
	Processingspeed float64
	Processingtime  int64
	Firsteventtime  time.Time
	Lasteventtime   time.Time
}

type Process struct {
	Name           sql.NullString
	Catalog        sql.NullString
	Process        sql.NullString
	Processid      sql.NullInt64
	Processtype    sql.NullString
	Pid            sql.NullString
	Port           sql.NullString
	Uid            sql.NullString
	Servername     sql.NullString
	Ip             sql.NullString
	Firsteventtime sql.NullTime
	Lasteventtime  sql.NullTime
}
